AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Travel GPT Backend Lambda Function

Globals:
  Function:
    Timeout: 30
    Runtime: python3.11
    MemorySize: 256
    Environment:
      Variables:
        OPENAI_SECRET_NAME: travel-gpt/openai-api-key

Resources:
  TravelGPTFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: api_handler.lambda_handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /travel-gpt
            Method: GET
        ApiPostEvent:
          Type: Api
          Properties:
            Path: /travel-gpt
            Method: POST
        ApiOptionsEvent:
          Type: Api
          Properties:
            Path: /travel-gpt
            Method: OPTIONS
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - secretsmanager:DescribeSecret
              Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:travel-gpt/openai-api-key-*'

Outputs:
  TravelGPTApi:
    Description: "API Gateway endpoint URL for Travel GPT"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/travel-gpt"
  TravelGPTFunction:
    Description: "Travel GPT Lambda Function ARN"
    Value: !GetAtt TravelGPTFunction.Arn
